### ISSUE TITLE
Правки

### ISSUE THREAD

**Issue by soul-wish** [Destors/Destors.github.io#1]
- почему нравится больше чистый CSS?
- можешь сделать так что бы я смог на телефоне открыть твою страничку?

**Comment by Destors** [comment]
Препроцессоры возможно удобно на больших проектах, но я с такими пока не работал. На чистом css читабельность чужого кода, выше чем чтение вложенных блоков LESS.
Адаптив, попробую сделать.

**Comment by soul-wish** [comment]
Ок, спасибо.
