### ISSUE TITLE
По Английской версии сайта

### ISSUE THREAD

**Issue by Goraksd** [Destors/Destors.github.io#5]
при нажатии на кнопки перекидывает в начало страницы. В конце не Read more а читить больше
![image](https://user-images.githubusercontent.com/40791707/42446800-3fe24e6a-8380-11e8-9ffd-bd2137091115.png)
/сс @soul-wish

**Comment by Destors** [comment]
спасибо, займусь.

**Comment by Destors** [comment]
исправлено
